window.IKKI_PROJECTS = [
{"id":"dongnae-cafe-1","title":"동래구 카페","year":"2025","category":"commercial","categoryKo":"상업공간","location":"부산 동래구","mapQuery":"부산 동래구","image":"../ikki-archive/img/01.jpg","instagram":"https://www.instagram.com/reel/DJjVA0aprEH/","summary":"계단을 따라 이어지는 이끼 언덕과 자갈 바닥으로 실내에 자연의 흐름을 만든 프로젝트입니다."},
{"id":"yangsan-home","title":"경남 양산 주거공간","year":"2025","category":"residential","categoryKo":"주거공간","location":"경남 양산","mapQuery":"경남 양산","image":"../ikki-archive/img/03.jpg","instagram":"https://www.instagram.com/p/DSuJ24hkyQN/","summary":"유리 구조물 안의 수목과 이끼, 돌을 조합해 실내에 작은 정원을 구성한 주거 프로젝트입니다."},
{"id":"ulsan-home-1","title":"울산 주거공간","year":"2025","category":"residential","categoryKo":"주거공간","location":"울산","mapQuery":"울산","image":"../ikki-archive/img/02.jpg","instagram":"https://www.instagram.com/p/DSJ30r2E5DX/","summary":"수납 가구 하부를 따라 이끼와 돌, 식재를 연결한 주거공간 프로젝트입니다."},
{"id":"daegu-exco-hall2","title":"대구 엑스코 제2전시장","year":"2025","category":"exhibition","categoryKo":"전시·팝업","location":"대구 EXCO","mapQuery":"대구 엑스코","image":"../ikki-archive/img/05.jpg","instagram":"https://www.instagram.com/p/DLZf88cRAoL/","summary":"전시 공간의 동선을 따라 곡선형 플랜터와 식재를 구성한 프로젝트입니다."},
{"id":"home-2026-1","title":"주거공간","year":"2026","category":"residential","categoryKo":"주거공간","location":"비공개 주거공간","mapQuery":"","image":"../ikki-archive/img/04.jpg","instagram":"https://www.instagram.com/p/DTjFRuNE0Pt/","summary":"유리 너머로 보이는 수목과 이끼 바닥을 중심으로 구성한 주거공간 프로젝트입니다."},
{"id":"dongnae-cafe-2","title":"동래구 카페","year":"2025","category":"commercial","categoryKo":"상업공간","location":"부산 동래구","mapQuery":"부산 동래구","image":"../ikki-archive/img/08.jpg","instagram":"https://www.instagram.com/p/DJlnCpVxS7d/","summary":"카페 내부의 단차와 시선을 활용해 이끼 언덕을 중심 장면으로 만든 프로젝트입니다."},
{"id":"home-2026-2","title":"주거공간","year":"2026","category":"residential","categoryKo":"주거공간","location":"비공개 주거공간","mapQuery":"","image":"../ikki-archive/img/06.jpg","instagram":"https://www.instagram.com/p/DUzY00FE3f5/","summary":"고사리와 이끼, 돌을 플랜터 안에 밀도 있게 구성한 주거공간 프로젝트입니다."},
{"id":"ulsan-home-2","title":"울산 주거공간","year":"2025","category":"residential","categoryKo":"주거공간","location":"울산","mapQuery":"울산","image":"../ikki-archive/img/07.jpg","instagram":"https://www.instagram.com/p/DM98_LlzlrD/","summary":"실내 한쪽에 이끼와 넓은 잎 식물을 배치해 자연스럽게 공간의 경계를 만든 프로젝트입니다."},
{"id":"daegu-exco-build","title":"대구 엑스코 시공 현장","year":"2025","category":"exhibition","categoryKo":"전시·팝업","location":"대구 EXCO","mapQuery":"대구 엑스코","image":"../ikki-archive/img/10.jpg","instagram":"https://www.instagram.com/reel/DLUl9JHxfhd/","summary":"대구 엑스코 전시 공간에서 진행한 플랜터 식재 및 현장 시공 과정입니다."},
{"id":"ulsan-home-3","title":"울산 주거공간","year":"2025","category":"residential","categoryKo":"주거공간","location":"울산","mapQuery":"울산","image":"../ikki-archive/img/09.jpg","instagram":"https://www.instagram.com/p/DMUmUskRQpq/","summary":"벽면 수납장 하부의 여백을 활용해 식재를 연결한 주거공간 프로젝트입니다."}
];